// Date: 06/08/2014 20:07:57
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package common.cout970.UltraTech.client.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelSteamTurbine extends ModelBase
{
	//fields
	ModelRenderer chamber;
	ModelRenderer rotor;
	ModelRenderer dynamo;
	ModelRenderer base;
	ModelRenderer suport1;
	ModelRenderer suport2;
	ModelRenderer suport3;
	ModelRenderer suport4;
	ModelRenderer wing1;
	ModelRenderer wing2;
	ModelRenderer wing3;
	ModelRenderer wing4;
	ModelRenderer basetop;

	public ModelSteamTurbine()
	{
		textureWidth = 64;
		textureHeight = 64;

		chamber = new ModelRenderer(this, 0, 44);
		chamber.addBox(0F, -3F, 0F, 14, 6, 14);
		chamber.setRotationPoint(-7F, 12F, -7F);
		chamber.setTextureSize(64, 64);
		chamber.mirror = true;
		setRotation(chamber, 0F, 0F, 0F);
		rotor = new ModelRenderer(this, 0, 33);
		rotor.addBox(-1F, -6F, -1F, 2, 8, 2);
		rotor.setRotationPoint(0F, 16F, 0F);
		rotor.setTextureSize(64, 64);
		rotor.mirror = true;
		setRotation(rotor, 0F, 0F, 0F);
		dynamo = new ModelRenderer(this, 9, 30);
		dynamo.addBox(-4F, 2F, -4F, 8, 5, 8);
		dynamo.setRotationPoint(0F, 16F, 0F);
		dynamo.setTextureSize(64, 64);
		dynamo.mirror = true;
		setRotation(dynamo, 0F, 0F, 0F);
		base = new ModelRenderer(this, 0, 0);
		base.addBox(-8F, 0F, -8F, 16, 1, 16);
		base.setRotationPoint(0F, 23F, 0F);
		base.setTextureSize(64, 64);
		base.mirror = true;
		setRotation(base, 0F, 0F, 0F);
		suport1 = new ModelRenderer(this, 0, 17);
		suport1.addBox(-8F, -7F, -8F, 1, 14, 1);
		suport1.setRotationPoint(0F, 16F, 0F);
		suport1.setTextureSize(64, 64);
		suport1.mirror = true;
		setRotation(suport1, 0F, 0F, 0F);
		suport2 = new ModelRenderer(this, 0, 17);
		suport2.addBox(-8F, -7F, 7F, 1, 14, 1);
		suport2.setRotationPoint(0F, 16F, 0F);
		suport2.setTextureSize(64, 64);
		suport2.mirror = true;
		setRotation(suport2, 0F, 0F, 0F);
		suport3 = new ModelRenderer(this, 0, 17);
		suport3.addBox(7F, -7F, -8F, 1, 14, 1);
		suport3.setRotationPoint(0F, 16F, 0F);
		suport3.setTextureSize(64, 64);
		suport3.mirror = true;
		setRotation(suport3, 0F, 0F, 0F);
		suport4 = new ModelRenderer(this, 0, 17);
		suport4.addBox(7F, -7F, 7F, 1, 14, 1);
		suport4.setRotationPoint(0F, 16F, 0F);
		suport4.setTextureSize(64, 64);
		suport4.mirror = true;
		setRotation(suport4, 0F, 0F, 0F);
		wing1 = new ModelRenderer(this, 10, 18);
		wing1.addBox(-0.5F, 0F, 1F, 1, 3, 5);
		wing1.setRotationPoint(0F, 10F, 0F);
		wing1.setTextureSize(64, 64);
		wing1.mirror = true;
		setRotation(wing1, 0F, 0F, 0.1745329F);
		wing2 = new ModelRenderer(this, 10, 18);
		wing2.addBox(-0.5F, 0F, -6F, 1, 3, 5);
		wing2.setRotationPoint(0F, 10F, 0F);
		wing2.setTextureSize(64, 64);
		wing2.mirror = true;
		setRotation(wing2, 0F, 0F, -0.1745329F);
		wing3 = new ModelRenderer(this, 23, 18);
		wing3.addBox(1F, 0F, -0.5F, 5, 3, 1);
		wing3.setRotationPoint(0F, 10F, 0F);
		wing3.setTextureSize(64, 64);
		wing3.mirror = true;
		setRotation(wing3, 0.1745329F, 0F, 0F);
		wing4 = new ModelRenderer(this, 23, 18);
		wing4.addBox(-6F, 0F, -0.5F, 5, 3, 1);
		wing4.setRotationPoint(0F, 10F, 0F);
		wing4.setTextureSize(64, 64);
		wing4.mirror = true;
		setRotation(wing4, -0.1745329F, 0F, 0F);
		basetop = new ModelRenderer(this, 0, 0);
		basetop.addBox(-8F, 0F, -8F, 16, 1, 16);
		basetop.setRotationPoint(0F, 8F, 0F);
		basetop.setTextureSize(64, 64);
		basetop.mirror = true;
		setRotation(basetop, 0F, 0F, 0F);
	}

	public void render(float f5)
	{
		chamber.render(f5);
		dynamo.render(f5);
		base.render(f5);
		suport1.render(f5);
		suport2.render(f5);
		suport3.render(f5);
		suport4.render(f5);
//		basetop.render(f5);
	}

	public void renderRotor(float f5){
		rotor.render(f5);
		wing1.render(f5);
		wing2.render(f5);
		wing3.render(f5);
		wing4.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z)
	{
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity e)
	{
		super.setRotationAngles(f, f1, f2, f3, f4, f5, e);
	}

}
