// Date: 01/07/2014 17:44:17
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package common.cout970.UltraTech.client.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelPump extends ModelBase
{
  //fields
    ModelRenderer tank;
    ModelRenderer pipe;
    ModelRenderer base;
    ModelRenderer motor;
    ModelRenderer deco1;
    ModelRenderer deco2;
    ModelRenderer suport;
    ModelRenderer suport1;
    ModelRenderer suport2;
    ModelRenderer suport3;
    ModelRenderer base2;
  
  public ModelPump()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      tank = new ModelRenderer(this, 0, 0);
      tank.addBox(-8F, -40F, -8F, 16, 16, 16);
      tank.setRotationPoint(0F, 16F, 0F);
      tank.setTextureSize(128, 64);
      tank.mirror = true;
      setRotation(tank, 0F, 0F, 0F);
      pipe = new ModelRenderer(this, 0, 36);
      pipe.addBox(-2F, -4F, -2F, 4, 24, 4);
      pipe.setRotationPoint(0F, 0F, 0F);
      pipe.setTextureSize(128, 64);
      pipe.mirror = true;
      setRotation(pipe, 0F, 0F, 0F);
      base = new ModelRenderer(this, 16, 46);
      base.addBox(-8F, 6F, -8F, 16, 2, 16);
      base.setRotationPoint(0F, 16F, 0F);
      base.setTextureSize(128, 64);
      base.mirror = true;
      setRotation(base, 0F, 0F, 0F);
      motor = new ModelRenderer(this, 64, 0);
      motor.addBox(-4F, 8F, -4F, 8, 12, 8);
      motor.setRotationPoint(0F, 0F, 0F);
      motor.setTextureSize(128, 64);
      motor.mirror = true;
      setRotation(motor, 0F, 0F, 0F);
      deco1 = new ModelRenderer(this, 80, 50);
      deco1.addBox(-6F, -6F, -6F, 12, 2, 12);
      deco1.setRotationPoint(0F, 0F, 0F);
      deco1.setTextureSize(128, 64);
      deco1.mirror = true;
      setRotation(deco1, 0F, 0F, 0F);
      deco2 = new ModelRenderer(this, 80, 50);
      deco2.addBox(-6F, 20F, -6F, 12, 2, 12);
      deco2.setRotationPoint(0F, 0F, 0F);
      deco2.setTextureSize(128, 64);
      deco2.mirror = true;
      setRotation(deco2, 0F, 0F, 0F);
      suport = new ModelRenderer(this, 98, 0);
      suport.addBox(-8F, -6F, 7F, 1, 28, 1);
      suport.setRotationPoint(0F, 0F, 0F);
      suport.setTextureSize(128, 64);
      suport.mirror = true;
      setRotation(suport, 0F, 0F, 0F);
      suport1 = new ModelRenderer(this, 98, 0);
      suport1.addBox(7F, -6F, 7F, 1, 28, 1);
      suport1.setRotationPoint(0F, 0F, 0F);
      suport1.setTextureSize(128, 64);
      suport1.mirror = true;
      setRotation(suport1, 0F, 0F, 0F);
      suport2 = new ModelRenderer(this, 98, 0);
      suport2.addBox(-8F, -6F, -8F, 1, 28, 1);
      suport2.setRotationPoint(0F, 0F, 0F);
      suport2.setTextureSize(128, 64);
      suport2.mirror = true;
      setRotation(suport2, 0F, 0F, 0F);
      suport3 = new ModelRenderer(this, 98, 0);
      suport3.addBox(7F, -6F, -8F, 1, 28, 1);
      suport3.setRotationPoint(0F, 0F, 0F);
      suport3.setTextureSize(128, 64);
      suport3.mirror = true;
      setRotation(suport3, 0F, 0F, 0F);
      base2 = new ModelRenderer(this, 48, 20);
      base2.addBox(-8F, -8F, -8F, 16, 2, 16);
      base2.setRotationPoint(0F, 0F, 0F);
      base2.setTextureSize(128, 64);
      base2.mirror = true;
      setRotation(base2, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    tank.render(f5);
    pipe.render(f5);
    base.render(f5);
    deco1.render(f5);
    deco2.render(f5);
    suport.render(f5);
    suport1.render(f5);
    suport2.render(f5);
    suport3.render(f5);
    base2.render(f5);
  }
  
  public void renderMotor(float f5){
	  motor.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity e)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, e);
  }

}
