// Date: 07/08/2014 15:54:19
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package common.cout970.UltraTech.client.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelBottle extends ModelBase
{
  //fields
    ModelRenderer top;
    ModelRenderer suport1;
    ModelRenderer suport2;
    ModelRenderer suport3;
    ModelRenderer valve;
    ModelRenderer frame1;
    ModelRenderer frame2;
    ModelRenderer frame3;
    ModelRenderer center;
  
  public ModelBottle()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      top = new ModelRenderer(this, 0, 26);
      top.addBox(-6F, 0F, -2F, 12, 2, 4);
      top.setRotationPoint(0F, 0F, 0F);
      top.setTextureSize(64, 32);
      top.mirror = true;
      setRotation(top, 0F, 0F, 0F);
      suport1 = new ModelRenderer(this, 0, 22);
      suport1.addBox(0F, 0F, -1F, 1, 1, 2);
      suport1.setRotationPoint(0F, -1F, 0F);
      suport1.setTextureSize(64, 32);
      suport1.mirror = true;
      setRotation(suport1, 0F, 0F, 0F);
      suport2 = new ModelRenderer(this, 0, 18);
      suport2.addBox(1F, 0F, -1F, 4, 1, 2);
      suport2.setRotationPoint(0F, -2F, 0F);
      suport2.setTextureSize(64, 32);
      suport2.mirror = true;
      setRotation(suport2, 0F, 0F, 0F);
      suport3 = new ModelRenderer(this, 0, 22);
      suport3.addBox(5F, 0F, -1F, 1, 1, 2);
      suport3.setRotationPoint(0F, -1F, 0F);
      suport3.setTextureSize(64, 32);
      suport3.mirror = true;
      setRotation(suport3, 0F, 0F, 0F);
      valve = new ModelRenderer(this, 0, 14);
      valve.addBox(-5F, 0F, -1F, 2, 1, 2);
      valve.setRotationPoint(0F, -1F, 0F);
      valve.setTextureSize(64, 32);
      valve.mirror = true;
      setRotation(valve, 0F, 0F, 0F);
      frame1 = new ModelRenderer(this, 0, 0);
      frame1.addBox(0F, 2F, -2F, 2, 10, 4);
      frame1.setRotationPoint(-6F, 0F, 0F);
      frame1.setTextureSize(64, 32);
      frame1.mirror = true;
      setRotation(frame1, 0F, 0F, 0F);
      frame2 = new ModelRenderer(this, 0, 0);
      frame2.addBox(4F, 2F, -2F, 2, 10, 4);
      frame2.setRotationPoint(0F, 0F, 0F);
      frame2.setTextureSize(64, 32);
      frame2.mirror = true;
      setRotation(frame2, 0F, 0F, 0F);
      frame3 = new ModelRenderer(this, 40, 0);
      frame3.addBox(-4F, 10F, -2F, 8, 2, 4);
      frame3.setRotationPoint(0F, 0F, 0F);
      frame3.setTextureSize(64, 32);
      frame3.mirror = true;
      setRotation(frame3, 0F, 0F, 0F);
      center = new ModelRenderer(this, 15, 0);
      center.addBox(-4F, 2F, -2F, 8, 8, 4);
      center.setRotationPoint(0F, 0F, 0F);
      center.setTextureSize(64, 32);
      center.mirror = true;
      setRotation(center, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    top.render(f5);
    suport1.render(f5);
    suport2.render(f5);
    suport3.render(f5);
    valve.render(f5);
    frame1.render(f5);
    frame2.render(f5);
    frame3.render(f5);
    center.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5,Entity e)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5,e);
  }

}
