// Date: 21/08/2014 3:37:50
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package common.cout970.UltraTech.client.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelFlamethrower extends ModelBase
{
  //fields
    ModelRenderer base;
    ModelRenderer support1;
    ModelRenderer suport2;
    ModelRenderer heat;
    ModelRenderer tank;
    ModelRenderer pipe;
  
  public ModelFlamethrower()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      base = new ModelRenderer(this, 0, 0);
      base.addBox(0F, 0F, -8F, 3, 3, 32);
      base.setRotationPoint(0F, 0F, 0F);
      base.setTextureSize(128, 64);
      base.mirror = true;
      setRotation(base, 0F, 0F, 0F);
      support1 = new ModelRenderer(this, 0, 20);
      support1.addBox(0.48F, 0F, -6F, 2, 6, 3);
      support1.setRotationPoint(0F, 3F, 0F);
      support1.setTextureSize(128, 64);
      support1.mirror = true;
      setRotation(support1, 0F, 0F, 0F);
      suport2 = new ModelRenderer(this, 38, 0);
      suport2.addBox(0.5F, 0F, 8F, 2, 5, 2);
      suport2.setRotationPoint(0F, 3F, 0F);
      suport2.setTextureSize(128, 64);
      suport2.mirror = true;
      setRotation(suport2, 0F, 0F, 0F);
      heat = new ModelRenderer(this, 0, 0);
      heat.addBox(-0.5F, 0F, 12F, 4, 4, 6);
      heat.setRotationPoint(0F, -0.5F, 5F);
      heat.setTextureSize(128, 64);
      heat.mirror = true;
      setRotation(heat, 0F, 0F, 0F);
      tank = new ModelRenderer(this, 0, 10);
      tank.addBox(-0.5F, -7F, -4.5F, 4, 6, 4);
      tank.setRotationPoint(0F, 0F, 0F);
      tank.setTextureSize(128, 64);
      tank.mirror = true;
      setRotation(tank, 0F, 0F, 0F);
      pipe = new ModelRenderer(this, 0, 29);
      pipe.addBox(1F, -1F, -3F, 1, 1, 1);
      pipe.setRotationPoint(0F, 0F, 0F);
      pipe.setTextureSize(128, 64);
      pipe.mirror = true;
      setRotation(pipe, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    base.render(f5);
    support1.render(f5);
    suport2.render(f5);
    heat.render(f5);
    tank.render(f5);
    pipe.render(f5);
  }

  public void renderItem(float f5){
	  base.render(f5);
	  support1.render(f5);
	  suport2.render(f5);
	  heat.render(f5);
	  tank.render(f5);
	  pipe.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity e)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, e);
  }

}
