// Date: 12/09/2014 23:01:27
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package common.cout970.UltraTech.client.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelLaserTurret extends ModelBase
{
  //fields
    ModelRenderer gireBase;
    ModelRenderer suport1;
    ModelRenderer suport2;
    ModelRenderer eje;
    ModelRenderer head1;
    ModelRenderer head2;
    ModelRenderer backhead;
    ModelRenderer shoot;
  
  public ModelLaserTurret()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      gireBase = new ModelRenderer(this, 0, 19);
      gireBase.addBox(-3F, -3F, -3F, 6, 6, 10);
      gireBase.setRotationPoint(0F, 14F, 0F);
      gireBase.setTextureSize(64, 64);
      gireBase.mirror = true;
      setRotation(gireBase, 0F, 0F, 0F);
      suport1 = new ModelRenderer(this, 0, 0);
      suport1.addBox(-2F, 0F, -8F, 4, 3, 16);
      suport1.setRotationPoint(0F, 21F, 0F);
      suport1.setTextureSize(64, 64);
      suport1.mirror = true;
      setRotation(suport1, 0F, 0F, 0F);
      suport2 = new ModelRenderer(this, 0, 35);
      suport2.addBox(-8F, 0F, -2F, 16, 3, 4);
      suport2.setRotationPoint(0F, 21F, 0F);
      suport2.setTextureSize(64, 64);
      suport2.mirror = true;
      setRotation(suport2, 0F, 0F, 0F);
      eje = new ModelRenderer(this, 0, 42);
      eje.addBox(-1F, 1F, -1F, 2, 6, 2);
      eje.setRotationPoint(0F, 14F, 0F);
      eje.setTextureSize(64, 64);
      eje.mirror = true;
      setRotation(eje, 0F, 0F, 0F);
      head1 = new ModelRenderer(this, 0, 52);
      head1.addBox(-2F, -2F, -11F, 4, 4, 8);
      head1.setRotationPoint(0F, 14F, 0F);
      head1.setTextureSize(64, 64);
      head1.mirror = true;
      setRotation(head1, 0F, 0F, 0F);
      head2 = new ModelRenderer(this, 24, 54);
      head2.addBox(-1F, -1F, -19F, 2, 2, 8);
      head2.setRotationPoint(0F, 14F, 0F);
      head2.setTextureSize(64, 64);
      head2.mirror = true;
      setRotation(head2, 0F, 0F, 0F);
      backhead = new ModelRenderer(this, 54, 0);
      backhead.addBox(-2F, -2F, 7F, 4, 4, 1);
      backhead.setRotationPoint(0F, 14F, 0F);
      backhead.setTextureSize(64, 64);
      backhead.mirror = true;
      setRotation(backhead, 0F, 0F, 0F);
      shoot = new ModelRenderer(this, 40, 0);
      shoot.addBox(-1.5F, -1.5F, -23F, 3, 3, 4);
      shoot.setRotationPoint(0F, 14F, 0F);
      shoot.setTextureSize(64, 64);
      shoot.mirror = true;
      setRotation(shoot, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    //static
    suport1.render(f5);
    suport2.render(f5);
    eje.render(f5);
  }
  
  public void renderDynamic(float f5){
	  //dynamic
	gireBase.render(f5);
    head1.render(f5);
    head2.render(f5);
    backhead.render(f5);
    shoot.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

}
