// Date: 29/08/2014 18:25:26
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package common.cout970.UltraTech.client.models;

import common.cout970.UltraTech.util.LogHelper;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelBatteryIO extends ModelBase
{
	//fields
	ModelRenderer FIO;
	ModelRenderer BIO;
	ModelRenderer LIO;
	ModelRenderer RIO;

	public ModelBatteryIO()
	{
		textureWidth = 36;
		textureHeight = 16;

		FIO = new ModelRenderer(this, 0, 0);
		FIO.addBox(-4F, -4F, 0F, 8, 8, 1);
		FIO.setRotationPoint(0F, 16F, -8F);
		FIO.setTextureSize(36, 16);
		FIO.mirror = true;
		setRotation(FIO, 0F, 0F, 0F);
		BIO = new ModelRenderer(this, 0, 0);
		BIO.addBox(-4F, -4F, 0F, 8, 8, 1);
		BIO.setRotationPoint(0F, 16F, 7F);
		BIO.setTextureSize(36, 16);
		BIO.mirror = true;
		setRotation(BIO, 0F, 0F, 0F);
		LIO = new ModelRenderer(this, 18, 0);
		LIO.addBox(0F, -4F, -4F, 1, 8, 8);
		LIO.setRotationPoint(7F, 16F, 0F);
		LIO.setTextureSize(36, 16);
		LIO.mirror = true;
		setRotation(LIO, 0F, 0F, 0F);
		RIO = new ModelRenderer(this, 18, 0);
		RIO.addBox(0F, -4F, -4F, 1, 8, 8);
		RIO.setRotationPoint(-8F, 16F, 0F);
		RIO.setTextureSize(36, 16);
		RIO.mirror = true;
		setRotation(RIO, 0F, 0F, 0F);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
	{
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		FIO.render(f5);
		BIO.render(f5);
		LIO.render(f5);
		RIO.render(f5);
	}

	public void render(float f5,boolean[] sides){
		if(sides == null)return;
		if(sides[0])FIO.render(f5);
		if(sides[1])BIO.render(f5);
		if(sides[2])LIO.render(f5);
		if(sides[3])RIO.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z)
	{
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
	{
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	}

}
