// Date: 22/03/2014 16:53:17
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package common.cout970.UltraTech.client.models;

import common.cout970.UltraTech.util.fluids.FluidUtils;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.world.IBlockAccess;

public class ModelFluidPipe extends ModelBase
{
  //fields
    ModelRenderer base;
    ModelRenderer sideF;
    ModelRenderer sideB;
    ModelRenderer sideL;
    ModelRenderer sideR;
    ModelRenderer sideU;
    ModelRenderer sideD;
  
  public ModelFluidPipe()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      base = new ModelRenderer(this, 0, 0);
      base.addBox(-3F, -3F, -3F, 6, 6, 6);
      base.setRotationPoint(0F, 16F, 0F);
      base.setTextureSize(64, 32);
      base.mirror = true;
      setRotation(base, 0F, 0F, 0F);
      sideF = new ModelRenderer(this, 23, 21);
      sideF.addBox(-3F, -3F, -3F, 6, 6, 5);
      sideF.setRotationPoint(0F, 16F, -5F);
      sideF.setTextureSize(64, 32);
      sideF.mirror = true;
      setRotation(sideF, 0F, 0F, 0F);
      sideB = new ModelRenderer(this, 23, 21);
      sideB.addBox(-3F, -3F, -3F, 6, 6, 5);
      sideB.setRotationPoint(0F, 16F, 6F);
      sideB.setTextureSize(64, 32);
      sideB.mirror = true;
      setRotation(sideB, 0F, 0F, 0F);
      sideL = new ModelRenderer(this, 0, 20);
      sideL.addBox(-3F, -3F, -3F, 5, 6, 6);
      sideL.setRotationPoint(6F, 16F, 0F);
      sideL.setTextureSize(64, 32);
      sideL.mirror = true;
      setRotation(sideL, 0F, 0F, 0F);
      sideR = new ModelRenderer(this, 0, 20);
      sideR.addBox(-3F, -3F, -3F, 5, 6, 6);
      sideR.setRotationPoint(-5F, 16F, 0F);
      sideR.setTextureSize(64, 32);
      sideR.mirror = true;
      setRotation(sideR, 0F, 0F, 0F);
      sideU = new ModelRenderer(this, 24, 0);
      sideU.addBox(-3F, -3F, -3F, 6, 5, 6);
      sideU.setRotationPoint(0F, 11F, 0F);
      sideU.setTextureSize(64, 32);
      sideU.mirror = true;
      setRotation(sideU, 0F, 0F, 0F);
      sideD = new ModelRenderer(this, 24, 0);
      sideD.addBox(-3F, -3F, -3F, 6, 5, 6);
      sideD.setRotationPoint(0F, 22F, 0F);
      sideD.setTextureSize(64, 32);
      sideD.mirror = true;
      setRotation(sideD, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5,entity);
    base.render(f5);
    sideF.render(f5);
    sideB.render(f5);
    sideL.render(f5);
    sideR.render(f5);
    sideU.render(f5);
    sideD.render(f5);
  }
  
  public void renderModel(float f5, IBlockAccess w, int x, int y, int z) {
		
		boolean renderUp = FluidUtils.CanPassFluid(
				w.getTileEntity(x, y, z),
				w.getTileEntity(x, y + 1, z));
		boolean renderDown = FluidUtils.CanPassFluid(
				w.getTileEntity(x, y, z),
				w.getTileEntity(x, y - 1, z));
		boolean renderFront = FluidUtils.CanPassFluid(
				w.getTileEntity(x, y, z),
				w.getTileEntity(x, y, z + 1));
		boolean renderBack = FluidUtils.CanPassFluid(
				w.getTileEntity(x, y, z),
				w.getTileEntity(x, y, z - 1));
		boolean renderRight = FluidUtils.CanPassFluid(
				w.getTileEntity(x, y, z),
				w.getTileEntity(x + 1, y, z));
		boolean renderLeft = FluidUtils.CanPassFluid(
				w.getTileEntity(x, y, z),
				w.getTileEntity(x - 1, y, z));

		int i = 0;
		if(renderRight){
			i++;
			sideR.render(f5);
		}
		if(renderLeft){
			i++;
			sideL.render(f5);
		}
		if(renderBack){
			i++;
			sideF.render(f5);
		}
		if(renderFront){
			i++;
			sideB.render(f5);
		}
		if(renderUp){
			i++;
			sideU.render(f5);
		}
		if(renderDown){
			i++;
			sideD.render(f5);
		}
		if(i != 6)base.render(f5);
	}
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5,Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
