// Date: 16/06/2014 16:28:03
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package common.cout970.UltraTech.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelPipeIn extends ModelBase
{
  //fields
    ModelRenderer center;
    ModelRenderer top;
    ModelRenderer bottom;
    ModelRenderer front;
    ModelRenderer back;
    ModelRenderer left;
    ModelRenderer right;
  
  public ModelPipeIn()
  {
    textureWidth = 24;
    textureHeight = 12;
    
      center = new ModelRenderer(this, 0, 0);
      center.addBox(-3F, -3F, -3F, 6, 6, 6);
      center.setRotationPoint(0F, 16F, 0F);
      center.setTextureSize(24, 12);
      center.mirror = true;
      setRotation(center, 0F, 0F, 0F);
      top = new ModelRenderer(this, 0, 0);
      top.addBox(-3F, -6F, -3F, 6, 3, 6);
      top.setRotationPoint(0F, 16F, 0F);
      top.setTextureSize(24, 12);
      top.mirror = true;
      setRotation(top, 0F, 0F, 0F);
      bottom = new ModelRenderer(this, 0, 0);
      bottom.addBox(-3F, 3F, -3F, 6, 3, 6);
      bottom.setRotationPoint(0F, 16F, 0F);
      bottom.setTextureSize(24, 12);
      bottom.mirror = true;
      setRotation(bottom, 0F, 0F, 0F);
      front = new ModelRenderer(this, 0, 0);
      front.addBox(-3F, -3F, -6F, 6, 6, 3);
      front.setRotationPoint(0F, 16F, 0F);
      front.setTextureSize(24, 12);
      front.mirror = true;
      setRotation(front, 0F, 0F, 0F);
      back = new ModelRenderer(this, 0, 0);
      back.addBox(-3F, -3F, 3F, 6, 6, 3);
      back.setRotationPoint(0F, 16F, 0F);
      back.setTextureSize(24, 12);
      back.mirror = true;
      setRotation(back, 0F, 0F, 0F);
      left = new ModelRenderer(this, 0, 0);
      left.addBox(3F, -3F, -3F, 3, 6, 6);
      left.setRotationPoint(0F, 16F, 0F);
      left.setTextureSize(24, 12);
      left.mirror = true;
      setRotation(left, 0F, 0F, 0F);
      right = new ModelRenderer(this, 0, 0);
      right.addBox(-6F, -3F, -3F, 3, 6, 6);
      right.setRotationPoint(0F, 16F, 0F);
      right.setTextureSize(24, 12);
      right.mirror = true;
      setRotation(right, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    center.render(f5);
    top.render(f5);
    bottom.render(f5);
    front.render(f5);
    back.render(f5);
    left.render(f5);
    right.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity e)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, e);
  }

}
