// Date: 19/05/2014 15:18:06
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package common.cout970.UltraTech.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelPump extends ModelBase
{
  //fields
    ModelRenderer base1;
    ModelRenderer base2;
    ModelRenderer base3;
    ModelRenderer base4;
    ModelRenderer base5;
    ModelRenderer pipe;
    ModelRenderer motor;
    ModelRenderer rotor;
    ModelRenderer tank;
    ModelRenderer tube1;
    ModelRenderer tube2;
  
  public ModelPump()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      base1 = new ModelRenderer(this, 0, 0);
      base1.addBox(-0.5F, 0F, -0.5F, 1, 49, 1);
      base1.setRotationPoint(0F, -24F, 0F);
      base1.setTextureSize(128, 64);
      base1.mirror = true;
      setRotation(base1, 0.1396263F, 0F, -0.1396263F);
      base2 = new ModelRenderer(this, 0, 0);
      base2.addBox(-0.5F, 0F, -0.5F, 1, 49, 1);
      base2.setRotationPoint(0F, -24F, 0F);
      base2.setTextureSize(128, 64);
      base2.mirror = true;
      setRotation(base2, 0.1396263F, 0F, 0.1396263F);
      base3 = new ModelRenderer(this, 0, 0);
      base3.addBox(-0.5F, 0F, -0.5F, 1, 49, 1);
      base3.setRotationPoint(0F, -24F, 0F);
      base3.setTextureSize(128, 64);
      base3.mirror = true;
      setRotation(base3, -0.1396263F, 0F, 0.1396263F);
      base4 = new ModelRenderer(this, 0, 0);
      base4.addBox(-0.5F, 0F, -0.5F, 1, 49, 1);
      base4.setRotationPoint(0F, -24F, 0F);
      base4.setTextureSize(128, 64);
      base4.mirror = true;
      setRotation(base4, -0.1396263F, 0F, -0.1396263F);
      base5 = new ModelRenderer(this, 64, 0);
      base5.addBox(-8F, 0F, -8F, 16, 1, 16);
      base5.setRotationPoint(0F, 23F, 0F);
      base5.setTextureSize(128, 64);
      base5.mirror = true;
      setRotation(base5, 0F, 0F, 0F);
      pipe = new ModelRenderer(this, 6, 18);
      pipe.addBox(-1F, 0F, -1F, 2, 44, 2);
      pipe.setRotationPoint(0F, -21F, 0F);
      pipe.setTextureSize(128, 64);
      pipe.mirror = true;
      setRotation(pipe, 0F, 0F, 0F);
      motor = new ModelRenderer(this, 41, 0);
      motor.addBox(-2.5F, 0F, 2F, 5, 5, 6);
      motor.setRotationPoint(0F, 18F, 0F);
      motor.setTextureSize(128, 64);
      motor.mirror = true;
      setRotation(motor, 0F, 0F, 0F);
      rotor = new ModelRenderer(this, 59, 0);
      rotor.addBox(-0.5F, 0F, 1F, 1, 1, 1);
      rotor.setRotationPoint(0F, 20F, 0F);
      rotor.setTextureSize(128, 64);
      rotor.mirror = true;
      setRotation(rotor, 0F, 0F, 0F);
      tank = new ModelRenderer(this, 39, 12);
      tank.addBox(-3F, 0F, -8F, 6, 6, 6);
      tank.setRotationPoint(0F, 17F, 0F);
      tank.setTextureSize(128, 64);
      tank.mirror = true;
      setRotation(tank, 0F, 0F, 0F);
      tube1 = new ModelRenderer(this, 16, 0);
      tube1.addBox(-0.5F, 0F, -3F, 1, 2, 1);
      tube1.setRotationPoint(0F, 15F, -1F);
      tube1.setTextureSize(128, 64);
      tube1.mirror = true;
      setRotation(tube1, 0F, 0F, 0F);
      tube2 = new ModelRenderer(this, 24, 0);
      tube2.addBox(-0.5F, 0F, -4F, 1, 1, 3);
      tube2.setRotationPoint(0F, 14F, 0F);
      tube2.setTextureSize(128, 64);
      tube2.mirror = true;
      setRotation(tube2, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5,entity);
    base1.render(f5);
    base2.render(f5);
    base3.render(f5);
    base4.render(f5);
    base5.render(f5);
    pipe.render(f5);
    motor.render(f5);
    rotor.render(f5);
    tank.render(f5);
    tube1.render(f5);
    tube2.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5,Entity e)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5,e);
  }

}
