// Date: 18/06/2014 21:26:32
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package common.cout970.UltraTech.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelCenterPipe extends ModelBase
{
  //fields
    ModelRenderer UpRF;
    ModelRenderer UpFL;
    ModelRenderer UpLB;
    ModelRenderer UpBR;
    ModelRenderer UbarL;
    ModelRenderer UbarR;
    ModelRenderer UbarB;
    ModelRenderer UbarF;
    ModelRenderer HbarRF;
    ModelRenderer HbarBR;
    ModelRenderer HbarLB;
    ModelRenderer HbarFL;
    ModelRenderer DownRF;
    ModelRenderer DownBR;
    ModelRenderer DownLB;
    ModelRenderer DownFL;
    ModelRenderer DbarF;
    ModelRenderer DbarB;
    ModelRenderer DbarL;
    ModelRenderer DbarR;
  
  public ModelCenterPipe()
  {
    textureWidth = 10;
    textureHeight = 5;
    
      UpRF = new ModelRenderer(this, 0, 0);
      UpRF.addBox(-3F, -3F, -3F, 1, 1, 1);
      UpRF.setRotationPoint(0F, 16F, 0F);
      UpRF.setTextureSize(10, 5);
      UpRF.mirror = true;
      setRotation(UpRF, 0F, 0F, 0F);
      UpFL = new ModelRenderer(this, 0, 0);
      UpFL.addBox(2F, -3F, -3F, 1, 1, 1);
      UpFL.setRotationPoint(0F, 16F, 0F);
      UpFL.setTextureSize(10, 5);
      UpFL.mirror = true;
      setRotation(UpFL, 0F, 0F, 0F);
      UpLB = new ModelRenderer(this, 0, 0);
      UpLB.addBox(2F, -3F, 2F, 1, 1, 1);
      UpLB.setRotationPoint(0F, 16F, 0F);
      UpLB.setTextureSize(10, 5);
      UpLB.mirror = true;
      setRotation(UpLB, 0F, 0F, 0F);
      UpBR = new ModelRenderer(this, 0, 0);
      UpBR.addBox(-3F, -3F, 2F, 1, 1, 1);
      UpBR.setRotationPoint(0F, 16F, 0F);
      UpBR.setTextureSize(10, 5);
      UpBR.mirror = true;
      setRotation(UpBR, 0F, 0F, 0F);
      UbarL = new ModelRenderer(this, 0, 0);
      UbarL.addBox(2F, -3F, -2F, 1, 1, 4);
      UbarL.setRotationPoint(0F, 16F, 0F);
      UbarL.setTextureSize(10, 5);
      UbarL.mirror = true;
      setRotation(UbarL, 0F, 0F, 0F);
      UbarR = new ModelRenderer(this, 0, 0);
      UbarR.addBox(-3F, -3F, -2F, 1, 1, 4);
      UbarR.setRotationPoint(0F, 16F, 0F);
      UbarR.setTextureSize(10, 5);
      UbarR.mirror = true;
      setRotation(UbarR, 0F, 0F, 0F);
      UbarB = new ModelRenderer(this, 0, 0);
      UbarB.addBox(-2F, -3F, 2F, 4, 1, 1);
      UbarB.setRotationPoint(0F, 16F, 0F);
      UbarB.setTextureSize(10, 5);
      UbarB.mirror = true;
      setRotation(UbarB, 0F, 0F, 0F);
      UbarF = new ModelRenderer(this, 0, 0);
      UbarF.addBox(-2F, -3F, -3F, 4, 1, 1);
      UbarF.setRotationPoint(0F, 16F, 0F);
      UbarF.setTextureSize(10, 5);
      UbarF.mirror = true;
      setRotation(UbarF, 0F, 0F, 0F);
      HbarRF = new ModelRenderer(this, 0, 0);
      HbarRF.addBox(-3F, -2F, -3F, 1, 4, 1);
      HbarRF.setRotationPoint(0F, 16F, 0F);
      HbarRF.setTextureSize(10, 5);
      HbarRF.mirror = true;
      setRotation(HbarRF, 0F, 0F, 0F);
      HbarBR = new ModelRenderer(this, 0, 0);
      HbarBR.addBox(-3F, -2F, 2F, 1, 4, 1);
      HbarBR.setRotationPoint(0F, 16F, 0F);
      HbarBR.setTextureSize(10, 5);
      HbarBR.mirror = true;
      setRotation(HbarBR, 0F, 0F, 0F);
      HbarLB = new ModelRenderer(this, 0, 0);
      HbarLB.addBox(2F, -2F, 2F, 1, 4, 1);
      HbarLB.setRotationPoint(0F, 16F, 0F);
      HbarLB.setTextureSize(10, 5);
      HbarLB.mirror = true;
      setRotation(HbarLB, 0F, 0F, 0F);
      HbarFL = new ModelRenderer(this, 0, 0);
      HbarFL.addBox(2F, -2F, -3F, 1, 4, 1);
      HbarFL.setRotationPoint(0F, 16F, 0F);
      HbarFL.setTextureSize(10, 5);
      HbarFL.mirror = true;
      setRotation(HbarFL, 0F, 0F, 0F);
      DownRF = new ModelRenderer(this, 0, 0);
      DownRF.addBox(-3F, 2F, -3F, 1, 1, 1);
      DownRF.setRotationPoint(0F, 16F, 0F);
      DownRF.setTextureSize(10, 5);
      DownRF.mirror = true;
      setRotation(DownRF, 0F, 0F, 0F);
      DownBR = new ModelRenderer(this, 0, 0);
      DownBR.addBox(-3F, 2F, 2F, 1, 1, 1);
      DownBR.setRotationPoint(0F, 16F, 0F);
      DownBR.setTextureSize(10, 5);
      DownBR.mirror = true;
      setRotation(DownBR, 0F, 0F, 0F);
      DownLB = new ModelRenderer(this, 0, 0);
      DownLB.addBox(2F, 2F, 2F, 1, 1, 1);
      DownLB.setRotationPoint(0F, 16F, 0F);
      DownLB.setTextureSize(10, 5);
      DownLB.mirror = true;
      setRotation(DownLB, 0F, 0F, 0F);
      DownFL = new ModelRenderer(this, 0, 0);
      DownFL.addBox(2F, 2F, -3F, 1, 1, 1);
      DownFL.setRotationPoint(0F, 16F, 0F);
      DownFL.setTextureSize(10, 5);
      DownFL.mirror = true;
      setRotation(DownFL, 0F, 0F, 0F);
      DbarF = new ModelRenderer(this, 0, 0);
      DbarF.addBox(-2F, 2F, -3F, 4, 1, 1);
      DbarF.setRotationPoint(0F, 16F, 0F);
      DbarF.setTextureSize(10, 5);
      DbarF.mirror = true;
      setRotation(DbarF, 0F, 0F, 0F);
      DbarB = new ModelRenderer(this, 0, 0);
      DbarB.addBox(-2F, 2F, 2F, 4, 1, 1);
      DbarB.setRotationPoint(0F, 16F, 0F);
      DbarB.setTextureSize(10, 5);
      DbarB.mirror = true;
      setRotation(DbarB, 0F, 0F, 0F);
      DbarL = new ModelRenderer(this, 0, 0);
      DbarL.addBox(2F, 2F, -2F, 1, 1, 4);
      DbarL.setRotationPoint(0F, 16F, 0F);
      DbarL.setTextureSize(10, 5);
      DbarL.mirror = true;
      setRotation(DbarL, 0F, 0F, 0F);
      DbarR = new ModelRenderer(this, 0, 0);
      DbarR.addBox(-3F, 2F, -2F, 1, 1, 4);
      DbarR.setRotationPoint(0F, 16F, 0F);
      DbarR.setTextureSize(10, 5);
      DbarR.mirror = true;
      setRotation(DbarR, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    UpRF.render(f5);
    UpFL.render(f5);
    UpLB.render(f5);
    UpBR.render(f5);
    UbarL.render(f5);
    UbarR.render(f5);
    UbarB.render(f5);
    UbarF.render(f5);
    HbarRF.render(f5);
    HbarBR.render(f5);
    HbarLB.render(f5);
    HbarFL.render(f5);
    DownRF.render(f5);
    DownBR.render(f5);
    DownLB.render(f5);
    DownFL.render(f5);
    DbarF.render(f5);
    DbarB.render(f5);
    DbarL.render(f5);
    DbarR.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

  public void render(float f5, boolean[] a) {
	  if(a==null)return;	
	  UpRF.render(f5);
	  UpFL.render(f5);
	  UpLB.render(f5);
	  UpBR.render(f5);
	  if(a[1])UbarL.render(f5);
	  if(a[1])UbarR.render(f5);
	  if(a[1])UbarB.render(f5);
	  if(a[1])UbarF.render(f5);
	  if(a[2] && a[5])HbarRF.render(f5);
	  if(a[3] && a[5])HbarBR.render(f5);
	  if(a[3] && a[4])HbarLB.render(f5);
	  if(a[2] && a[4])HbarFL.render(f5);
	  DownRF.render(f5);
	  DownBR.render(f5);
	  DownLB.render(f5);
	  DownFL.render(f5);
	  if(a[0])DbarF.render(f5);
	  if(a[0])DbarB.render(f5);
	  if(a[0])DbarL.render(f5);
	  if(a[0])DbarR.render(f5);
  }

}
