// Date: 18/04/2014 19:09:52
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package common.cout970.UltraTech.models;


import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelTurbine extends ModelBase
{
  //fields
    ModelRenderer base_0;
    ModelRenderer top;
    ModelRenderer pilar1;
    ModelRenderer pilar2;
    ModelRenderer pilar3;
    ModelRenderer pilar4;
    ModelRenderer eje;
    ModelRenderer big1;
    ModelRenderer big2;
    ModelRenderer medium1;
    ModelRenderer medium2;
    ModelRenderer little1;
    ModelRenderer litle2;
    ModelRenderer glass1;
    ModelRenderer glass2;
    ModelRenderer glass3;
    ModelRenderer glass4;
  
  public ModelTurbine()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      base_0 = new ModelRenderer(this, 0, 46);
      base_0.addBox(0F, 0F, 0F, 16, 2, 16);
      base_0.setRotationPoint(-8F, 22F, -8F);
      base_0.setTextureSize(128, 64);
      base_0.mirror = true;
      setRotation(base_0, 0F, 0F, 0F);
      top = new ModelRenderer(this, 0, 28);
      top.addBox(-8F, 0F, -8F, 16, 1, 16);
      top.setRotationPoint(0F, 8F, 0F);
      top.setTextureSize(128, 64);
      top.mirror = true;
      setRotation(top, 0F, 0F, 0F);
      pilar1 = new ModelRenderer(this, 65, 50);
      pilar1.addBox(0F, 0F, 0F, 1, 13, 1);
      pilar1.setRotationPoint(-8F, 9F, -8F);
      pilar1.setTextureSize(128, 64);
      pilar1.mirror = true;
      setRotation(pilar1, 0F, 0F, 0F);
      pilar2 = new ModelRenderer(this, 65, 50);
      pilar2.addBox(0F, 0F, 0F, 1, 13, 1);
      pilar2.setRotationPoint(7F, 9F, 7F);
      pilar2.setTextureSize(128, 64);
      pilar2.mirror = true;
      setRotation(pilar2, 0F, 0F, 0F);
      pilar3 = new ModelRenderer(this, 65, 50);
      pilar3.addBox(0F, 0F, 0F, 1, 13, 1);
      pilar3.setRotationPoint(-8F, 9F, 7F);
      pilar3.setTextureSize(128, 64);
      pilar3.mirror = true;
      setRotation(pilar3, 0F, 0F, 0F);
      pilar4 = new ModelRenderer(this, 65, 50);
      pilar4.addBox(0F, 0F, 0F, 1, 13, 1);
      pilar4.setRotationPoint(7F, 9F, -8F);
      pilar4.setTextureSize(128, 64);
      pilar4.mirror = true;
      setRotation(pilar4, 0F, 0F, 0F);
      eje = new ModelRenderer(this, 0, 0);
      eje.addBox(-1F, 0F, -1F, 2, 13, 2);
      eje.setRotationPoint(0F, 9F, 0F);
      eje.setTextureSize(128, 64);
      eje.mirror = true;
      setRotation(eje, 0F, 0F, 0F);
      big1 = new ModelRenderer(this, 33, 12);
      big1.addBox(-1F, 0F, -7F, 2, 1, 14);
      big1.setRotationPoint(0F, 18F, 0F);
      big1.setTextureSize(128, 64);
      big1.mirror = true;
      setRotation(big1, 0F, 0F, 0F);
      big2 = new ModelRenderer(this, 0, 24);
      big2.addBox(-7F, -2F, -1F, 14, 1, 2);
      big2.setRotationPoint(0F, 20F, 0F);
      big2.setTextureSize(128, 64);
      big2.mirror = true;
      setRotation(big2, 0F, 0F, 0F);
      medium1 = new ModelRenderer(this, 37, 0);
      medium1.addBox(-1F, 0F, -5F, 2, 1, 10);
      medium1.setRotationPoint(0F, 15F, 0F);
      medium1.setTextureSize(128, 64);
      medium1.mirror = true;
      setRotation(medium1, 0F, 0F, 0F);
      medium2 = new ModelRenderer(this, 0, 20);
      medium2.addBox(-5F, 0F, -1F, 10, 1, 2);
      medium2.setRotationPoint(0F, 15F, 0F);
      medium2.setTextureSize(128, 64);
      medium2.mirror = true;
      setRotation(medium2, 0F, 0F, 0F);
      little1 = new ModelRenderer(this, 20, 0);
      little1.addBox(-1F, 0F, -3F, 2, 1, 6);
      little1.setRotationPoint(0F, 12F, 0F);
      little1.setTextureSize(128, 64);
      little1.mirror = true;
      setRotation(little1, 0F, 0F, 0F);
      litle2 = new ModelRenderer(this, 0, 16);
      litle2.addBox(-3F, 0F, -1F, 6, 1, 2);
      litle2.setRotationPoint(0F, 12F, 0F);
      litle2.setTextureSize(128, 64);
      litle2.mirror = true;
      setRotation(litle2, 0F, 0F, 0F);
      glass1 = new ModelRenderer(this, 70, 37);
      glass1.addBox(0F, 0F, 0F, 0, 13, 14);
      glass1.setRotationPoint(-7F, 9F, -7F);
      glass1.setTextureSize(128, 64);
      glass1.mirror = true;
      setRotation(glass1, 0F, 0F, 0F);
      glass2 = new ModelRenderer(this, 70, 37);
      glass2.addBox(0F, 0F, -7F, 0, 13, 14);
      glass2.setRotationPoint(7F, 9F, 0F);
      glass2.setTextureSize(128, 64);
      glass2.mirror = true;
      setRotation(glass2, 0F, 0F, 0F);
      glass3 = new ModelRenderer(this, 70, 38);
      glass3.addBox(0F, 0F, 0F, 14, 13, 0);
      glass3.setRotationPoint(-7F, 9F, -7F);
      glass3.setTextureSize(128, 64);
      glass3.mirror = true;
      setRotation(glass3, 0F, 0F, 0F);
      glass4 = new ModelRenderer(this, 70, 38);
      glass4.addBox(0F, 0F, 0F, 14, 13, 0);
      glass4.setRotationPoint(-7F, 9F, 7F);
      glass4.setTextureSize(128, 64);
      glass4.mirror = true;
      setRotation(glass4, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    base_0.render(f5);
    top.render(f5);
    pilar1.render(f5);
    pilar2.render(f5);
    pilar3.render(f5);
    pilar4.render(f5);
    eje.render(f5);
    big1.render(f5);
    big2.render(f5);
    medium1.render(f5);
    medium2.render(f5);
    little1.render(f5);
    litle2.render(f5);
    glass1.render(f5);
    glass2.render(f5);
    glass3.render(f5);
    glass4.render(f5);
  }
  
  public void renderStatic(float f5){
	  base_0.render(f5);
	    top.render(f5);
	    pilar1.render(f5);
	    pilar2.render(f5);
	    pilar3.render(f5);
	    pilar4.render(f5);
	    glass1.render(f5);
	    glass2.render(f5);
	    glass3.render(f5);
	    glass4.render(f5);
  }
  
  public void renderDynamic(float f5, float rot){
	  eje.rotateAngleY = rot;
	  big1.rotateAngleY = rot;
	  big2.rotateAngleY = rot;
	  medium1.rotateAngleY = rot;
	  medium2.rotateAngleY = rot;
	  little1.rotateAngleY = rot; 
	  litle2.rotateAngleY = rot;
	  
	  eje.render(f5);
	  big1.render(f5);
	  big2.render(f5);
	  medium1.render(f5);
	  medium2.render(f5);
	  little1.render(f5);
	  litle2.render(f5);
	  
	  eje.rotateAngleY = 0;
	  big1.rotateAngleY = 0;
	  big2.rotateAngleY = 0;
	  medium1.rotateAngleY = 0;
	  medium2.rotateAngleY = 0;
	  little1.rotateAngleY = 0; 
	  litle2.rotateAngleY = 0;
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5,Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5,entity);
  }

}
