// Date: 02/01/2014 11:45:20
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package common.cout970.UltraTech.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelWindMill extends ModelBase
{
  //fields
    ModelRenderer base;
    ModelRenderer pilar;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer fan1;
    ModelRenderer fan2;
    ModelRenderer fan3;
    ModelRenderer fan4;
    ModelRenderer fan5;
    ModelRenderer fan6;
  
  public ModelWindMill()
  {
	  textureWidth = 64;
	    textureHeight = 128;
	    
	      base = new ModelRenderer(this, 0, 96);
	      base.addBox(-8F, 0F, -8F, 16, 16, 16);
	      base.setRotationPoint(0F, 8F, 0F);
	      base.setTextureSize(64, 128);
	      base.mirror = true;
	      setRotation(base, 0F, 0F, 0F);
	      pilar = new ModelRenderer(this, 0, 37);
	      pilar.addBox(-3F, -64F, -3F, 6, 53, 6);
	      pilar.setRotationPoint(0F, 19F, 0F);
	      pilar.setTextureSize(64, 128);
	      pilar.mirror = true;
	      setRotation(pilar, 0F, 0F, 0F);
	      Shape3 = new ModelRenderer(this, 0, 0);
	      Shape3.addBox(-3F, -3F, -7F, 6, 6, 14);
	      Shape3.setRotationPoint(0F, -48F, 0F);
	      Shape3.setTextureSize(64, 128);
	      Shape3.mirror = true;
	      setRotation(Shape3, 0F, 0F, 0F);
	      Shape4 = new ModelRenderer(this, 24, 80);
	      Shape4.addBox(-1F, -1F, 0F, 2, 2, 14);
	      Shape4.setRotationPoint(0F, -48F, 0F);
	      Shape4.setTextureSize(64, 128);
	      Shape4.mirror = true;
	      setRotation(Shape4, 0F, 0F, 0F);
	      Shape5 = new ModelRenderer(this, 24, 42);
	      Shape5.addBox(-2F, -2F, 10F, 4, 4, 3);
	      Shape5.setRotationPoint(0F, -48F, 0F);
	      Shape5.setTextureSize(64, 128);
	      Shape5.mirror = true;
	      setRotation(Shape5, 0F, 0F, 0F);
	      fan1 = new ModelRenderer(this, 24, 49);
	      fan1.addBox(-1F, 0F, 0F, 2, 22, 1);
	      fan1.setRotationPoint(0F, -48F, 11F);
	      fan1.setTextureSize(64, 128);
	      fan1.mirror = true;
	      setRotation(fan1, 0F, 0F, 2F);
	      fan2 = new ModelRenderer(this, 24, 49);
	      fan2.addBox(-1F, 0F, 0F, 2, 22, 1);
	      fan2.setRotationPoint(0F, -48F, 11F);
	      fan2.setTextureSize(64, 128);
	      fan2.mirror = true;
	      setRotation(fan2, 0F, 0F, 0F);
	      fan3 = new ModelRenderer(this, 24, 49);
	      fan3.addBox(-1F, 0F, 0F, 2, 22, 1);
	      fan3.setRotationPoint(0F, -48F, 11F);
	      fan3.setTextureSize(64, 128);
	      fan3.mirror = true;
	      setRotation(fan3, 0F, 0F, -2F);
	      fan4 = new ModelRenderer(this, 24, 49);
	      fan4.addBox(-1F, 0F, 0F, 2, 22, 1);
	      fan4.setRotationPoint(0F, -48F, 11F);
	      fan4.setTextureSize(64, 128);
	      fan4.mirror = true;
	      setRotation(fan4, 0F, 0F, -1F);
	      fan5 = new ModelRenderer(this, 24, 49);
	      fan5.addBox(-1F, 0F, 0F, 2, 22, 1);
	      fan5.setRotationPoint(0F, -48F, 11F);
	      fan5.setTextureSize(64, 128);
	      fan5.mirror = true;
	      setRotation(fan5, 0F, 0F, 1F);
	      fan6 = new ModelRenderer(this, 24, 49);
	      fan6.addBox(-1F, 0F, 0F, 2, 22, 1);
	      fan6.setRotationPoint(0F, -48F, 11F);
	      fan6.setTextureSize(64, 128);
	      fan6.mirror = true;
	      setRotation(fan6, 0F, 0F, -3F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    base.render(f5);
    pilar.render(f5);
    Shape3.render(f5);
    Shape4.render(f5);
    Shape5.render(f5);
    fan1.render(f5);
    fan2.render(f5);
    fan3.render(f5);
    fan4.render(f5);
    fan5.render(f5);
    fan6.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5,Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5,entity);
  }

}
