// Date: 16/06/2014 16:00:24
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package common.cout970.UltraTech.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelPipe extends ModelBase
{
  //fields
    ModelRenderer fullU;
    ModelRenderer fullD;
    ModelRenderer fullF;
    ModelRenderer fullB;
    ModelRenderer fullR;
    ModelRenderer fullL;
    ModelRenderer conU;
    ModelRenderer conD;
    ModelRenderer conF;
    ModelRenderer conB;
    ModelRenderer conR;
    ModelRenderer conL;
  
  public ModelPipe()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      fullU = new ModelRenderer(this, 0, 21);
      fullU.addBox(-3F, -8F, -3F, 6, 5, 6);
      fullU.setRotationPoint(0F, 16F, 0F);
      fullU.setTextureSize(64, 32);
      fullU.mirror = true;
      setRotation(fullU, 0F, 0F, 0F);
      fullD = new ModelRenderer(this, 0, 21);
      fullD.addBox(-3F, 3F, -3F, 6, 5, 6);
      fullD.setRotationPoint(0F, 16F, 0F);
      fullD.setTextureSize(64, 32);
      fullD.mirror = true;
      setRotation(fullD, 0F, 0F, 0F);
      fullF = new ModelRenderer(this, 24, 21);
      fullF.addBox(-3F, -3F, -8F, 6, 6, 5);
      fullF.setRotationPoint(0F, 16F, 0F);
      fullF.setTextureSize(64, 32);
      fullF.mirror = true;
      setRotation(fullF, 0F, 0F, 0F);
      fullB = new ModelRenderer(this, 24, 21);
      fullB.addBox(-3F, -3F, 3F, 6, 6, 5);
      fullB.setRotationPoint(0F, 16F, 0F);
      fullB.setTextureSize(64, 32);
      fullB.mirror = true;
      setRotation(fullB, 0F, 0F, 0F);
      fullR = new ModelRenderer(this, 42, 0);
      fullR.addBox(-8F, -3F, -3F, 5, 6, 6);
      fullR.setRotationPoint(0F, 16F, 0F);
      fullR.setTextureSize(64, 32);
      fullR.mirror = true;
      setRotation(fullR, 0F, 0F, 0F);
      fullL = new ModelRenderer(this, 42, 0);
      fullL.addBox(3F, -3F, -3F, 5, 6, 6);
      fullL.setRotationPoint(0F, 16F, 0F);
      fullL.setTextureSize(64, 32);
      fullL.mirror = true;
      setRotation(fullL, 0F, 0F, 0F);
      conU = new ModelRenderer(this, 0, 0);
      conU.addBox(-4F, -8F, -4F, 8, 2, 8);
      conU.setRotationPoint(0F, 16F, 0F);
      conU.setTextureSize(64, 32);
      conU.mirror = true;
      setRotation(conU, 0F, 0F, 0F);
      conD = new ModelRenderer(this, 0, 0);
      conD.addBox(-4F, 6F, -4F, 8, 2, 8);
      conD.setRotationPoint(0F, 16F, 0F);
      conD.setTextureSize(64, 32);
      conD.mirror = true;
      setRotation(conD, 0F, 0F, 0F);
      conF = new ModelRenderer(this, 0, 11);
      conF.addBox(-4F, -4F, -8F, 8, 8, 2);
      conF.setRotationPoint(0F, 16F, 0F);
      conF.setTextureSize(64, 32);
      conF.mirror = true;
      setRotation(conF, 0F, 0F, 0F);
      conB = new ModelRenderer(this, 0, 11);
      conB.addBox(-4F, -4F, 6F, 8, 8, 2);
      conB.setRotationPoint(0F, 16F, 0F);
      conB.setTextureSize(64, 32);
      conB.mirror = true;
      setRotation(conB, 0F, 0F, 0F);
      conR = new ModelRenderer(this, 29, 5);
      conR.addBox(-8F, -4F, -4F, 2, 8, 8);
      conR.setRotationPoint(0F, 16F, 0F);
      conR.setTextureSize(64, 32);
      conR.mirror = true;
      setRotation(conR, 0F, 0F, 0F);
      conL = new ModelRenderer(this, 29, 5);
      conL.addBox(6F, -4F, -4F, 2, 8, 8);
      conL.setRotationPoint(0F, 16F, 0F);
      conL.setTextureSize(64, 32);
      conL.mirror = true;
      setRotation(conL, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5,entity);
    fullU.render(f5);
    fullD.render(f5);
    fullF.render(f5);
    fullB.render(f5);
    fullR.render(f5);
    fullL.render(f5);
    conU.render(f5);
    conD.render(f5);
    conF.render(f5);
    conB.render(f5);
    conR.render(f5);
    conL.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5,Entity entity)
  {
	  super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

  public void render(float f5,boolean[] a, boolean[] b) {
	  if(a == null)return;
	  if(a[1])fullU.render(f5);
	  if(a[0])fullD.render(f5);
	  if(a[2])fullF.render(f5);
	  if(a[3])fullB.render(f5);
	  if(a[4])fullL.render(f5);
	  if(a[5])fullR.render(f5);

	  if(b == null)return;
	  if(b[0])conU.render(f5);
	  if(b[1])conD.render(f5); 
	  if(b[2])conB.render(f5);
	  if(b[3])conF.render(f5);
	  if(b[4])conR.render(f5);
	  if(b[5])conL.render(f5);
  }

}
