// Date: 16/06/2014 16:14:24
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX




package common.cout970.UltraTech.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelPipeBase extends ModelBase
{
	//fields
	ModelRenderer baseU;
	ModelRenderer baseD;
	ModelRenderer baseF;
	ModelRenderer baseB;
	ModelRenderer baseR;
	ModelRenderer baseL;

	public ModelPipeBase()
	{
		textureWidth = 12;
		textureHeight = 6;

		baseU = new ModelRenderer(this, -6, 0);
		baseU.addBox(-3F, -3F, -3F, 6, 0, 6);
		baseU.setRotationPoint(0F, 16F, 0F);
		baseU.setTextureSize(12, 6);
		baseU.mirror = true;
		setRotation(baseU, 0F, 0F, 0F);
		baseD = new ModelRenderer(this, -6, 0);
		baseD.addBox(-3F, 3F, -3F, 6, 0, 6);
		baseD.setRotationPoint(0F, 16F, 0F);
		baseD.setTextureSize(12, 6);
		baseD.mirror = true;
		setRotation(baseD, 0F, 0F, 0F);
		baseF = new ModelRenderer(this, 0, 0);
		baseF.addBox(-3F, -3F, -3F, 6, 6, 0);
		baseF.setRotationPoint(0F, 16F, 0F);
		baseF.setTextureSize(12, 6);
		baseF.mirror = true;
		setRotation(baseF, 0F, 0F, 0F);
		baseB = new ModelRenderer(this, 0, 0);
		baseB.addBox(-3F, -3F, 3F, 6, 6, 0);
		baseB.setRotationPoint(0F, 16F, 0F);
		baseB.setTextureSize(12, 6);
		baseB.mirror = true;
		setRotation(baseB, 0F, 0F, 0F);
		baseR = new ModelRenderer(this, 0, -6);
		baseR.addBox(-3F, -3F, -3F, 0, 6, 6);
		baseR.setRotationPoint(0F, 16F, 0F);
		baseR.setTextureSize(12, 6);
		baseR.mirror = true;
		setRotation(baseR, 0F, 0F, 0F);
		baseL = new ModelRenderer(this, 0, -6);
		baseL.addBox(3F, -3F, -3F, 0, 6, 6);
		baseL.setRotationPoint(0F, 16F, 0F);
		baseL.setTextureSize(12, 6);
		baseL.mirror = true;
		setRotation(baseL, 0F, 0F, 0F);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
	{
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		baseU.render(f5);
		baseD.render(f5);
		baseF.render(f5);
		baseB.render(f5);
		baseR.render(f5);
		baseL.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z)
	{
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity e)
	{
		super.setRotationAngles(f, f1, f2, f3, f4, f5, e);
	}

	public void render(float f5, boolean[] b) {
		if(b == null)return;
		if(!b[1])baseU.render(f5);
		if(!b[0])baseD.render(f5);
		if(!b[2])baseF.render(f5);
		if(!b[3])baseB.render(f5);
		if(!b[5])baseR.render(f5);
		if(!b[4])baseL.render(f5);
	}

}
