// Date: 08/03/2014 21:36:06
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package common.cout970.UltraTech.models;

import api.cout970.UltraTech.FTpower.PowerUtils;
import common.cout970.UltraTech.lib.RenderUtil;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.ResourceLocation;
import net.minecraft.world.IBlockAccess;

public class ModelCable extends ModelBase
{
  //fields
    ModelRenderer base;
    ModelRenderer sideR;
    ModelRenderer sideL;
    ModelRenderer sideF;
    ModelRenderer sideB;
    ModelRenderer sideU;
    ModelRenderer sideD;
  
  public ModelCable()
  {
    textureWidth = 48;
    textureHeight = 48;
    
      base = new ModelRenderer(this, 0, 0);
      base.addBox(-2F, -2F, -2F, 4, 4, 4);
      base.setRotationPoint(0F, 16F, 0F);
      base.setTextureSize(48, 48);
      base.mirror = true;
      setRotation(base, 0F, 0F, 0F);
      sideR = new ModelRenderer(this, 0, 8);
      sideR.addBox(-2F, -2F, -2F, 6, 4, 4);
      sideR.setRotationPoint(-6F, 16F, 0F);
      sideR.setTextureSize(48, 48);
      sideR.mirror = true;
      setRotation(sideR, 0F, 0F, 0F);
      sideL = new ModelRenderer(this, 0, 8);
      sideL.addBox(-2F, -2F, -2F, 6, 4, 4);
      sideL.setRotationPoint(4F, 16F, 0F);
      sideL.setTextureSize(48, 48);
      sideL.mirror = true;
      setRotation(sideL, 0F, 0F, 0F);
      sideF = new ModelRenderer(this, 0, 16);
      sideF.addBox(-2F, -2F, -2F, 4, 4, 6);
      sideF.setRotationPoint(0F, 16F, -6F);
      sideF.setTextureSize(48, 48);
      sideF.mirror = true;
      setRotation(sideF, 0F, 0F, 0F);
      sideB = new ModelRenderer(this, 0, 16);
      sideB.addBox(-2F, -2F, -2F, 4, 4, 6);
      sideB.setRotationPoint(0F, 16F, 4F);
      sideB.setTextureSize(48, 48);
      sideB.mirror = true;
      setRotation(sideB, 0F, 0F, 0F);
      sideU = new ModelRenderer(this, 0, 26);
      sideU.addBox(-2F, -2F, -2F, 4, 6, 4);
      sideU.setRotationPoint(0F, 10F, 0F);
      sideU.setTextureSize(48, 48);
      sideU.mirror = true;
      setRotation(sideU, 0F, 0F, 0F);
      sideD = new ModelRenderer(this, 0, 26);
      sideD.addBox(-2F, -2F, -2F, 4, 6, 4);
      sideD.setRotationPoint(0F, 20F, 0F);
      sideD.setTextureSize(48, 48);
      sideD.mirror = true;
      setRotation(sideD, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    base.render(f5);
    sideR.render(f5);
    sideL.render(f5);
    sideF.render(f5);
    sideB.render(f5);
    sideU.render(f5);
    sideD.render(f5);

  }
  
	public void renderModel(float f5, IBlockAccess w, int x, int y, int z) {
		
		boolean renderUp = PowerUtils.canConnectTo(
				w.getTileEntity(x, y, z),
				w.getTileEntity(x, y + 1, z));
		boolean renderDown = PowerUtils.canConnectTo(
				w.getTileEntity(x, y, z),
				w.getTileEntity(x, y - 1, z));
		boolean renderFront = PowerUtils.canConnectTo(
				w.getTileEntity(x, y, z),
				w.getTileEntity(x, y, z + 1));
		boolean renderBack = PowerUtils.canConnectTo(
				w.getTileEntity(x, y, z),
				w.getTileEntity(x, y, z - 1));
		boolean renderRight = PowerUtils.canConnectTo(
				w.getTileEntity(x, y, z),
				w.getTileEntity(x + 1, y, z));
		boolean renderLeft = PowerUtils.canConnectTo(
				w.getTileEntity(x, y, z),
				w.getTileEntity(x - 1, y, z));

		int i = 0;
		if(renderRight){
			i++;
			sideR.render(f5);
		}
		if(renderLeft){
			i++;
			sideL.render(f5);
		}
		if(renderBack){
			i++;
			sideF.render(f5);
		}
		if(renderFront){
			i++;
			sideB.render(f5);
		}
		if(renderUp){
			i++;
			sideU.render(f5);
		}
		if(renderDown){
			i++;
			sideD.render(f5);
		}
		
		if(i == 1){
			if(renderDown)RenderUtil.bindTexture(new ResourceLocation("ultratech:textures/misc/cable/base0.png"));
			if(renderUp)RenderUtil.bindTexture(new ResourceLocation("ultratech:textures/misc/cable/base1.png"));
			if(renderLeft)RenderUtil.bindTexture(new ResourceLocation("ultratech:textures/misc/cable/base2.png"));
			if(renderFront)RenderUtil.bindTexture(new ResourceLocation("ultratech:textures/misc/cable/base3.png"));
			if(renderRight)RenderUtil.bindTexture(new ResourceLocation("ultratech:textures/misc/cable/base4.png"));
			if(renderBack)RenderUtil.bindTexture(new ResourceLocation("ultratech:textures/misc/cable/base5.png"));
		}
		base.render(f5);
	}

  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }
}
