// Date: 26/02/2014 22:05:18
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX


package common.cout970.UltraTech.machines.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelTransformer extends ModelBase
{
  //fields
    ModelRenderer base1;
    ModelRenderer base2;
    ModelRenderer blue;
    ModelRenderer coppercoil;
    ModelRenderer cab1;
    ModelRenderer cab2;
    ModelRenderer cab3;
    ModelRenderer cab4;
  
  public ModelTransformer()
  {
    textureWidth = 128;
    textureHeight = 128;
    
      base1 = new ModelRenderer(this, 0, 0);
      base1.addBox(-8F, -8F, 0F, 16, 16, 2);
      base1.setRotationPoint(0F, 16F, -8F);
      base1.setTextureSize(128, 128);
      base1.mirror = true;
      setRotation(base1, 0F, 0F, 0F);
      base2 = new ModelRenderer(this, 0, 0);
      base2.addBox(-8F, -8F, 0F, 16, 16, 2);
      base2.setRotationPoint(0F, 16F, 6F);
      base2.setTextureSize(128, 128);
      base2.mirror = true;
      setRotation(base2, 0F, 0F, 0F);
      blue = new ModelRenderer(this, 0, 18);
      blue.addBox(-2F, -2F, 0F, 5, 12, 12);
      blue.setRotationPoint(-4F, 12F, -6F);
      blue.setTextureSize(128, 128);
      blue.mirror = true;
      setRotation(blue, 0F, 0F, 0F);
      coppercoil = new ModelRenderer(this, 0, 42);
      coppercoil.addBox(-2F, -2F, 0F, 5, 12, 12);
      coppercoil.setRotationPoint(3F, 12F, -6F);
      coppercoil.setTextureSize(128, 128);
      coppercoil.mirror = true;
      setRotation(coppercoil, 0F, 0F, 0F);
      cab1 = new ModelRenderer(this, 36, 0);
      cab1.addBox(0F, 0F, 0F, 4, 0, 12);
      cab1.setRotationPoint(-2F, 8F, -6F);
      cab1.setTextureSize(128, 128);
      cab1.mirror = true;
      setRotation(cab1, 0F, 0F, 0F);
      cab2 = new ModelRenderer(this, 36, 0);
      cab2.addBox(0F, 0F, 0F, 4, 0, 12);
      cab2.setRotationPoint(-2F, 24F, -6F);
      cab2.setTextureSize(128, 128);
      cab2.mirror = true;
      setRotation(cab2, 0F, 0F, 0F);
      cab3 = new ModelRenderer(this, 0, 54);
      cab3.addBox(0F, 0F, 0F, 0, 4, 12);
      cab3.setRotationPoint(8F, 14F, -6F);
      cab3.setTextureSize(128, 128);
      cab3.mirror = true;
      setRotation(cab3, 0F, 0F, 0F);
      cab4 = new ModelRenderer(this, 0, 54);
      cab4.addBox(0F, 0F, 0F, 0, 4, 12);
      cab4.setRotationPoint(-8F, 14F, -6F);
      cab4.setTextureSize(128, 128);
      cab4.mirror = true;
      setRotation(cab4, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    base1.render(f5);
    base2.render(f5);
    blue.render(f5);
    coppercoil.render(f5);
    cab1.render(f5);
    cab2.render(f5);
    cab3.render(f5);
    cab4.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5,Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
