// Date: 23/03/2014 2:34:59
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package common.cout970.UltraTech.machines.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelBoiler extends ModelBase
{
  //fields
    ModelRenderer base1;
    ModelRenderer base2;
    ModelRenderer base3;
    ModelRenderer base4;
    ModelRenderer tank;
  
  public ModelBoiler()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      base1 = new ModelRenderer(this, 0, 0);
      base1.addBox(-1F, -1F, -1F, 2, 2, 2);
      base1.setRotationPoint(-7F, 23F, 7F);
      base1.setTextureSize(64, 64);
      base1.mirror = true;
      setRotation(base1, 0F, 0F, 0F);
      base2 = new ModelRenderer(this, 0, 0);
      base2.addBox(-1F, -1F, -1F, 2, 2, 2);
      base2.setRotationPoint(-7F, 23F, -7F);
      base2.setTextureSize(64, 64);
      base2.mirror = true;
      setRotation(base2, 0F, 0F, 0F);
      base3 = new ModelRenderer(this, 0, 0);
      base3.addBox(-1F, -1F, -1F, 2, 2, 2);
      base3.setRotationPoint(7F, 23F, -7F);
      base3.setTextureSize(64, 64);
      base3.mirror = true;
      setRotation(base3, 0F, 0F, 0F);
      base4 = new ModelRenderer(this, 0, 0);
      base4.addBox(-1F, -1F, -1F, 2, 2, 2);
      base4.setRotationPoint(7F, 23F, 7F);
      base4.setTextureSize(64, 64);
      base4.mirror = true;
      setRotation(base4, 0F, 0F, 0F);
      tank = new ModelRenderer(this, 0, 0);
      tank.addBox(-6F, -5F, -6F, 16, 14, 16);
      tank.setRotationPoint(-2F, 13F, -2F);
      tank.setTextureSize(64, 64);
      tank.mirror = true;
      setRotation(tank, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    base1.render(f5);
    base2.render(f5);
    base3.render(f5);
    base4.render(f5);
    tank.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5,entity);
  }

}
