// Date: 17/11/2013 20:54:34
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package common.cout970.UltraTech.machines.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class SateliteModel extends ModelBase
{
  //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
  
  public SateliteModel()
  {
    textureWidth = 256;
    textureHeight = 32;
    
      Shape1 = new ModelRenderer(this, 0, 29);
      Shape1.addBox(0F, 0F, 0F, 80, 1, 2);
      Shape1.setRotationPoint(-40F, 16F, -1F);
      Shape1.setTextureSize(256, 32);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 113, 0);
      Shape2.addBox(-6F, 10F, -6F, 12, 12, 12);
      Shape2.setRotationPoint(0F, 0F, 0F);
      Shape2.setTextureSize(256, 32);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 0, 0);
      Shape3.addBox(0F, 0F, 0F, 28, 1, 16);
      Shape3.setRotationPoint(12F, 15F, -8F);
      Shape3.setTextureSize(256, 32);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
      Shape4 = new ModelRenderer(this, 0, 0);
      Shape4.addBox(0F, 0F, 0F, 28, 1, 16);
      Shape4.setRotationPoint(-40F, 15F, -8F);
      Shape4.setTextureSize(256, 32);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5,entity);
    Shape1.render(f5);
    Shape2.render(f5);
    Shape3.render(f5);
    Shape4.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity){
	      super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }
  
}
